# Generated by Django 5.0.6 on 2024-12-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='desc',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
